[template_input_parameters.project]
template_value = "#{project}#"
condition = "\\b[a-zA-Z]+\\b"
description = "Project Name"

[template_input_parameters.account_devsecops]
template_value = "#{account_devsecops}#"
condition = "^\\b\\d{12}\\b$"
description = "DevSecOps Account"

[template_input_parameters.region_devsecops]
template_value = "#{region_devsecops}#"
condition = "^[a-z]{2}-[a-z]{4,10}-\\d$"
description = "AWS Region"
default =  "us-east-2"

[template_input_parameters.slack_workspace_id]
template_value = "#{slack_workspace_id}#"
condition = "^T[A-Z0-9]{10}$"
description = "Slack workspace id"

[template_input_parameters.slack_channel_id]
template_value = "#{slack_channel_id}#"
condition = "^C[A-Z0-9]+$"
description = "Slack Channel Id"

[template_input_parameters.deployment_account]
template_value = "#{deployment_account}#"
condition = "^\\b\\d{12}\\b$"
description = "Deployment Account"

[template_input_parameters.deployment_region]
template_value = "#{deployment_region}#"
condition = "^[a-z]{2}-[a-z]{4,10}-\\d$"
description = "AWS Region"
default =  "us-east-2"

[template_input_parameters.partner_review_email]
template_value = "#{partner_review_email}#"
condition = "^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,63}$"
description = "Partner review email"

[template_input_parameters.environment]
template_value = "#{environment}#"
condition = "(dev|qa|stg|test|prod)"
description = "Environment allowed values (dev|qa|stg|test|prod)"

[project_properties]
project = "test"
account_devsecops = "225311078840"
region_devsecops = "us-east-2"
slack_workspace_id = "T06U1RD49J9"
slack_channel_id = "C06TY4P8X70"
deployment_account = "008893981236"
deployment_region = "us-east-2"
partner_review_email = "wilmar.velezl2@sophossolutions.com"
environment = "test"
