project_name: "codebuild_devsecops_iac_images"
framework_version: 2

account_devsecops: "#{account_devsecops}#"
region_devsecops: "#{region_devsecops}#"

chatops:
  slack_integration:
    enable: "true"
    slack_workspace_id: "#{slack_workspace_id}#"
    slack_channel_id: "#{slack_channel_id}#"

#Repository for project
repository_properties:
  repository_name: "cdkv2_devsecops_iac_codebuild_image"
  create_repository: "true"
  description: "Repository for Codebuild images for DevSecOps IaC Framework"
  branch: "master"

#Designed for pipeline
environments:
  - environment: 'dev'
    deployment_account: '#{deployment_account}#'
    deployment_region: "#{deployment_region}#"
    partner_review_email:
      - '#{partner_review_email}#'

ecr_repository_properties:
  - repository_name: "codebuild_devsecops_iac"
    lifecycle_rule:
      tags_prefix:
        - "prod"
        - "dev"
      max_images: 10
    resource_policy:
      accounts:
        - account_id: "123456789014" # change or add account to share image
          type: "read"
      ous:
        - id: "o-xxxxxxxxxx/*/ou-xxxx-xxxxxxxx/*"
          type: "read"
    deploy_app: "True"
    app_properties:
      build_spec_path: "../app/buildspec.yaml"
      version: "1.1.0"

# Tags definitions align with corporation instructions
tags:
  - key: 'Project'
    value: '#{project}#'
  - key: 'Environment'
    value: '#{environment}#'


